### ISSUE TITLE
wrong version in pdf file

### ISSUE THREAD

**Issue by AxelAhlborn** [danwerner21/TI99_22#1]
Hi, the file mainboard/mainboard_pcb_v0.96.pdf still shopws the old version v0.95
Greetings Axel

**Comment by danwerner21** [comment]
Should be corrected now -- thanks for letting me know!!

**Comment by AxelAhlborn** [comment]
Hi, thank you. On 0.96, the ATX Power support is missing (never mind, I use this: https://www.keelog.com/ti-99-4a-psu-modern-gray-au-replacement-ti-99-4a-power-supply-au-plug/). Page 3 of the pdf: Is it possible to use a different color ? If you print it on A4 you dont see anything because it is yellow on white. Greetings Axel

**Comment by AxelAhlborn** [comment]
I forgot that the issue is already closed... Sorry
