### ISSUE TITLE
Link to keycaps

### ISSUE THREAD

**Issue by shift838** [danwerner21/TI99_22#10]
Where did you find your keycaps from?  Do you have a link?

**Comment by danwerner21** [comment]
I had them custom manufactured at maxkeyboards.com.  The artwork file is in the keyboard folder in the repo -- TI-Keycaps.svg.

It was about $60 for the set in late 2022.  


MIX-COLOR-62-ISO-TP-6-25 -- Keycap Layout:  ISO 62-key (60%) ,  Bottom Row Layout:  6.25x Unit Spacebar ,  Keycap Print Method:  Top Print
