### ISSUE TITLE
GROM

### ISSUE THREAD

**Issue by SteveE3289** [danwerner21/TI99_22#11]
GROM sockets are label U26, U27, U28. The /4A GROMs are are labeled CD1255, CD1256, CD1257.

Is it safe to assume:

U26=CD1255
U27=CD1256
U28=CD1257

**Comment by danwerner21** [comment]
The GROM sockets are identical -- any GROM can go in any socket.   The chip select magic happens within the GROM itself.

**Comment by SteveE3289** [comment]
I did t know that! Learned something new about the TI today!

Thanks!
