### ISSUE TITLE
What is L8 ?

### ISSUE THREAD

**Issue by AxelAhlborn** [danwerner21/TI99_22#4]
Hi, need a Tip for L8, what is an Ferrite Bead). Where can I buy it ?
Greetings Axel

**Comment by danwerner21** [comment]
BOJACK 100 Pcs 3.5mm x 6mm x 0.8mm Axial Lead Ferrite Beads Inductors
https://a.co/d/0V739dD

Try these

Dan

**Comment by AxelAhlborn** [comment]
Thanks a lot :-)
