### ISSUE TITLE
Update links for Keyboard components

### ISSUE THREAD

**Issue by shift838** [danwerner21/TI99_22#8]
Need links updated for your keyboard components..

link does not work: Stabilizers (frame not used): | https://www.amazon.com/Genuine-Cherry-PCB-Snap-Stabilizers/dp/B085T8QZJC
link does not work: Stabilizers (Frame used) | https://www.amazon.com/dp/B082X4V9VC

Frame: | https://www.amazon.com/gp/product/B07MMB33WG

**Comment by danwerner21** [comment]
https://www.amazon.com/Genuine-Cherry-Snap-Stabilizers-Wires/dp/B0B5MZKRNR (no Frame)
https://www.amazon.com/Screw-Stabilizers-6-25u-Mechanical-Keyboard/dp/B098XF2HPK (Frame)

I will update the readme with these links.

Thanks for reporting the error!

Dan
